### PR TITLE
Fixed price format bug

### PR DESCRIPTION
**Pull request by nevmx**
💯

---
This change is [Reviewable](https://reviewable.io/reviews/ecse428-mcgill/backend/48)

### CODE REVIEW

**Comment by David-Liu-G** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/resources/assets/pages/postDetail.html, line 172 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/48#-KdMHXBvhcJV13QmA2wm:-KdMHXBvhcJV13QmA2wn:b1mc9ex) ([raw file](https://github.com/ecse428-mcgill/backend/blob/719d4682e021662c58c7ee431a05f47f9550ede6/src/main/resources/assets/pages/postDetail.html#L172)):*
> ```HTML
>                 book.price = "" + book.price + ".00";
>             } else if (/^\d*\.\d$/.test(book.price))  {
>                 book.price = "" + book.price + "0";
> ```

should be ".0" instead of "0"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/48)*

**Comment by nevmx** [comment]
If the price is #.# it will add a 0 so that it becomes #.#0

**Comment by David-Liu-G** [comment]
@nevmx merged

**Comment by chouttle** [comment]
*[src/main/resources/assets/pages/postDetail.html, line 172 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/48#-KdMHXBvhcJV13QmA2wm:-KdMK5Ctz3buk5e6F0Xb:b-q6p25f) ([raw file](https://github.com/ecse428-mcgill/backend/blob/719d4682e021662c58c7ee431a05f47f9550ede6/src/main/resources/assets/pages/postDetail.html#L172)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

should be ".0" instead of "0"?
</blockquote></details>

Don't think so, book.price already has a ".", it is of the form "##.#" and adding "0" makes it "##.#0"? It makes sense to me, is there an error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/48)*

**Comment by David-Liu-G** [comment]
@chouttle I was wrong and the commit has already been pushed to master

**Pull request merged**
