### PR TITLE
Max

### PR DESCRIPTION
**Pull request by nevmx**
💯

---
This change is [Reviewable](https://reviewable.io/reviews/ecse428-mcgill/backend/92)

### CODE REVIEW

**Comment by David-Liu-G** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdSyPpBWJC_VuEZmGUS:bxbuvni) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
> ```Java
>                     }
>                 }
>             }).start();
> ```

If sendActivationEmail() failed, we still have "success" returned? I think here we could just use synchronized process, because it's useless to have user's information inside database without sending out the email.

---

*[src/main/java/api/UserApi.java, line 190 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSzik67Y0ZZuhhVZr6:-KdSzik67Y0ZZuhhVZr7:bpx4jt9) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L190)):*
> ```Java
>     }
> 
>     private void sendActivationEmail(String name, String address, String userId, String code) throws Exception {
> ```

Could you combine this method with the one inside MailAPI together? For ex, add a new parameter "emailBody", so that we can just use the function inside MailApi

---

*[src/main/java/template/User/User.java, line 31 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdT-H6CUmCs9zTCKbOw:-KdT-H6CUmCs9zTCKbOx:bwszd9w) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/template/User/User.java#L31)):*
> ```Java
>     @NotNull
>     @Size(min = 1, max = 32)
>     private String activationCode;
> ```

is it UUID? if it is, then the length will be constant 32

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by nevmx** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdT1FU8ESTmpvBqoIpE:b-s68nsc) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

If sendActivationEmail() failed, we still have "success" returned? I think here we could just use synchronized process, because it's useless to have user's information inside database without sending out the email.
</blockquote></details>

The problem is that the user's browser will hang and freeze for a while if there is a problem while sending the activation email... To prevent that we either have to send the email in a separate thread ^ or use an asynchronous POST request

---

*[src/main/java/api/UserApi.java, line 190 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSzik67Y0ZZuhhVZr6:-KdT2_Xk6NETXhh58U4g:byjol8k) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L190)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

Could you combine this method with the one inside MailAPI together? For ex, add a new parameter "emailBody", so that we can just use the function inside MailApi
</blockquote></details>

I can do that, but I would just need to change the Mail API as the subject is hard coded in

---

*[src/main/java/template/User/User.java, line 31 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdT-H6CUmCs9zTCKbOw:-KdT2JvLvwJgYbpC0cju:b-dpm5ai) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/template/User/User.java#L31)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

is it UUID? if it is, then the length will be constant 32
</blockquote></details>

After activation, I made it change the activationCode to "null", but we can always leave the activation code in the database

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by David-Liu-G** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdT3zqeSoo1EIKgEFZp:b-kpgjx) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
<details><summary><i>Previously, nevmx (Max) wrote…</i></summary><blockquote>

The problem is that the user's browser will hang and freeze for a while if there is a problem while sending the activation email... To prevent that we either have to send the email in a separate thread ^ or use an asynchronous POST request
</blockquote></details>

I think it's better to add some "waiting indicator" to the browser and disable the "register" button while the user is waiting. Because we don't want user to click it multiple times and if a success message shows up much earlier than the actual email, the user may wanna click it several times.

---

*[src/main/java/api/UserApi.java, line 190 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSzik67Y0ZZuhhVZr6:-KdT4f7ee-mfSwAHiNyl:b9xa4bd) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L190)):*
<details><summary><i>Previously, nevmx (Max) wrote…</i></summary><blockquote>

I can do that, but I would just need to change the Mail API as the subject is hard coded in
</blockquote></details>

it's ok, change the function whatever you like

---

*[src/main/java/template/User/User.java, line 31 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdT-H6CUmCs9zTCKbOw:-KdT4l1u1Z4v1gff6Heh:b7om648) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/template/User/User.java#L31)):*
<details><summary><i>Previously, nevmx (Max) wrote…</i></summary><blockquote>

After activation, I made it change the activationCode to "null", but we can always leave the activation code in the database
</blockquote></details>

actually, can we use id as activation code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by nevmx** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdT9F2GHZHtIbjQXH8U:b5y5noc) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

I think it's better to add some "waiting indicator" to the browser and disable the "register" button while the user is waiting. Because we don't want user to click it multiple times and if a success message shows up much earlier than the actual email, the user may wanna click it several times.
</blockquote></details>

Alright, I can work on that, so I'll need to change the register POST request to use the jQuery ajax()

---

*[src/main/java/api/UserApi.java, line 190 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSzik67Y0ZZuhhVZr6:-KdT9PAIHiesa9wkxZmp:b-kqxpwl) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L190)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

it's ok, change the function whatever you like
</blockquote></details>

Alright, I'll work on that

---

*[src/main/java/template/User/User.java, line 31 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdT-H6CUmCs9zTCKbOw:-KdT8XW1-nnzCnhYRs3u:bouaykn) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/template/User/User.java#L31)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

actually, can we use id as activation code?
</blockquote></details>

Not really, in that case we're not really verifying the email because we pass around the user ID on the front end side, while the activation code is only sent by email.... A bad user could just get his own user id and go to /activate?userid=243531452456 and activate the account without ever going to the email

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by David-Liu-G** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdTA1-UMB2wY7GppDJv:b736w11) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
<details><summary><i>Previously, nevmx (Max) wrote…</i></summary><blockquote>

Alright, I can work on that, so I'll need to change the register POST request to use the jQuery ajax()
</blockquote></details>

A simpler way is add "show waiting icon and disable register button" to the onclick event of the  register button, and "remove waiting icon and enable register button" to call back function of POST request

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by nevmx** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/api/UserApi.java, line 89 at r1](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdSyPpBWJC_VuEZmGUR:-KdYqbLWYFuIZRdX_zJ2:b-l1yi81) ([raw file](https://github.com/ecse428-mcgill/backend/blob/38535bfc4a4e3dddaa85d9bf81f3416fa460d73c/src/main/java/api/UserApi.java#L89)):*
<details><summary><i>Previously, David-Liu-G wrote…</i></summary><blockquote>

A simpler way is add "show waiting icon and disable register button" to the onclick event of the  register button, and "remove waiting icon and enable register button" to call back function of POST request
</blockquote></details>

Done - I also replaced the 'please try again' javascript popup with an icon and a message under the form

---

*[src/main/resources/assets/pages/register.html, line 37 at r2](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdYqgfCdXIf2GmTq7KT:-KdYqgfCdXIf2GmTq7KU:ben0mur) ([raw file](https://github.com/ecse428-mcgill/backend/blob/0f46e2e29140b633adb5054577473ad31de574e1/src/main/resources/assets/pages/register.html#L37)):*
> ```HTML
>                type="password" required>
> 
>         <button id="create-account-button" class="w3-btn w3-green w3-round w3-margin-top" onclick="document.getElementById('create-account-button').disabled = true; $('#message_wait').removeAttr('hidden'); $('#message_error').attr('hidden', 'hidden');">Create Account</button>
> ```

This is the register button being disabled and reenabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Comment by nevmx** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/resources/assets/pages/register.html, line 58 at r2](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92#-KdYr3GIBo06HX5DkzZi:-KdYr3GJN367wbxJTChJ:b-bqwos7) ([raw file](https://github.com/ecse428-mcgill/backend/blob/0f46e2e29140b633adb5054577473ad31de574e1/src/main/resources/assets/pages/register.html#L58)):*
> ```HTML
>                         window.location.href = '../';
>                     } else {
>                         $('#message_error').removeAttr('hidden');
> ```

JS alert() replaced by an error message on the page

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ecse428-mcgill/backend/92)*

**Pull request closed without merging**
