### PR TITLE
Vivien

### PR DESCRIPTION
**Pull request by chouttle**
This change is [Reviewable](https://reviewable.io/reviews/ecse428-mcgill/backend/30)

### CODE REVIEW

**Comment by David-Liu-G** [comment]
Nice. The post.html under the template folder needs to be compiled by "gulp" before it can make effect. So I will make another commit just to compile it and then will merge it. @chouttle

**Comment by chouttle** [comment]
@David-Liu-G So that's why I couldn't see the changes I made, makes sense now. Thanks!

**Comment by David-Liu-G** [comment]
@chouttle I just found another issue, it doesn't make sense that user can use "contact seller" in his own posts (seller contacts himself). I think it's better that after the user log in, the "delete" button will replace "contact seller" button. @chouttle

**Comment by chouttle** [comment]
Agreed! Do you want me to modify it?

**Comment by David-Liu-G** [comment]
@chouttle just one line code, I will include it in the next commit along with the compiled template

**Pull request merged**
